anchor_version = "0.13.2"

[workspace]
members = [
    "token-lending/program",
]

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.mainnet]
spl_token_lending = "6wRfEcS6rcsLWVv4UDjq1bLDRepoAV6neiauzsUh8ufh"
